=== itsjackyboi/tavern-game/src/content/schemas/mayors.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "minItems": 1,
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "minLength": 1
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 40
      },
      "from": {
        "type": "integer",
        "minimum": -9007199254740991,
        "maximum": 9007199254740991
      },
      "to": {
        "type": "integer",
        "minimum": -9007199254740991,
        "maximum": 9007199254740991
      },
      "live": {
        "type": "boolean"
      }
    },
    "required": [
      "id",
      "name",
      "from",
      "to",
      "live"
    ],
    "additionalProperties": false
  }
}

=== itsjackyboi/tavern-game/src/content/data/mayors.json
[
  { "id": "cromwell", "name": "Cromwell", "from": 412, "to": 425, "live": false },
  { "id": "chestnut", "name": "Bronco Chestnut", "from": 425, "to": 427, "live": false },
  { "id": "galleyway", "name": "Glendolph Galleyway", "from": 427, "to": 451, "live": true },
  { "id": "thatcher-sr", "name": "Thomas Thatcher Sr.", "from": 452, "to": 463, "live": true }
]
